version: "3.9"
services:
  transmute:
    image: transmute/jws-test-suite-cli
    build:
      context: ./implementations/transmute
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
  # Commenting out, due to:
  # https://github.com/decentralized-identity/JWS-Test-Suite/runs/4157120036?check_suite_focus=true#step:5:788
  # danubetech:
  #   image: danubetech/ldsignatures-test-jws
  #   build:
  #     context: ./implementations/danubetech
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./data:/data
  spruce:
    image: spruce/jws-test-suite-cli
    build:
      context: ./implementations/spruce
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
