name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install
        run: npm i

      - name: Build Implementations
        run: npm run build

      - name: Clean Implementation Report
        run: npm run report:clean

      - name: Generate Implementation Report
        run: npm run report:generate

      - name: Deploy Implementation Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./data
